package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0

/**
 * AnalisisEstatico generated by hbm2java
 */
public class AnalisisEstatico  implements java.io.Serializable {


	private int idAnalisis;
    private Indicador indicador;
    private Float gradoSalida;
    private Float gradoEntrada;
    private Float centralidad;
    private Float centralidadNormalizada;
    private Float gradoEntradaNormalizado;
    private Float gradoSalidaNormalizado;

   public AnalisisEstatico() {
   }

	
   public AnalisisEstatico(int idAnalisis, Indicador indicador) {
       this.idAnalisis = idAnalisis;
       this.indicador = indicador;
   }
   public AnalisisEstatico(int idAnalisis, Indicador indicador, Float gradoSalida, Float gradoEntrada, Float centralidad, Float centralidadNormalizada, Float gradoEntradaNormalizado, Float gradoSalidaNormalizado) {
      this.idAnalisis = idAnalisis;
      this.indicador = indicador;
      this.gradoSalida = gradoSalida;
      this.gradoEntrada = gradoEntrada;
      this.centralidad = centralidad;
      this.centralidadNormalizada = centralidadNormalizada;
      this.gradoEntradaNormalizado = gradoEntradaNormalizado;
      this.gradoSalidaNormalizado = gradoSalidaNormalizado;
   }
  
   public int getIdAnalisis() {
       return this.idAnalisis;
   }
   
   public void setIdAnalisis(int idAnalisis) {
       this.idAnalisis = idAnalisis;
   }
   public Indicador getIndicador() {
       return this.indicador;
   }
   
   public void setIndicador(Indicador indicador) {
       this.indicador = indicador;
   }
   public Float getGradoSalida() {
       return this.gradoSalida;
   }
   
   public void setGradoSalida(Float gradoSalida) {
       this.gradoSalida = gradoSalida;
   }
   public Float getGradoEntrada() {
       return this.gradoEntrada;
   }
   
   public void setGradoEntrada(Float gradoEntrada) {
       this.gradoEntrada = gradoEntrada;
   }
   public Float getCentralidad() {
       return this.centralidad;
   }
   
   public void setCentralidad(Float centralidad) {
       this.centralidad = centralidad;
   }
   public Float getCentralidadNormalizada() {
       return this.centralidadNormalizada;
   }
   
   public void setCentralidadNormalizada(Float centralidadNormalizada) {
       this.centralidadNormalizada = centralidadNormalizada;
   }
   public Float getGradoEntradaNormalizado() {
       return this.gradoEntradaNormalizado;
   }
   
   public void setGradoEntradaNormalizado(Float gradoEntradaNormalizado) {
       this.gradoEntradaNormalizado = gradoEntradaNormalizado;
   }
   public Float getGradoSalidaNormalizado() {
       return this.gradoSalidaNormalizado;
   }
   
   public void setGradoSalidaNormalizado(Float gradoSalidaNormalizado) {
       this.gradoSalidaNormalizado = gradoSalidaNormalizado;
   }
}