package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {

	private int idAsignatura;
    private String nombreAsignatura;
    private Set indicadors = new HashSet(0);
    private Set preguntas = new HashSet(0);

   public Asignatura() {
   }

	
   public Asignatura(int idAsignatura) {
       this.idAsignatura = idAsignatura;
   }
   public Asignatura(int idAsignatura, String nombreAsignatura, Set indicadors, Set preguntas) {
      this.idAsignatura = idAsignatura;
      this.nombreAsignatura = nombreAsignatura;
      this.indicadors = indicadors;
      this.preguntas = preguntas;
   }
  
   public int getIdAsignatura() {
       return this.idAsignatura;
   }
   
   public void setIdAsignatura(int idAsignatura) {
       this.idAsignatura = idAsignatura;
   }
   public String getNombreAsignatura() {
       return this.nombreAsignatura;
   }
   
   public void setNombreAsignatura(String nombreAsignatura) {
       this.nombreAsignatura = nombreAsignatura;
   }
   public Set getIndicadors() {
       return this.indicadors;
   }
   
   public void setIndicadors(Set indicadors) {
       this.indicadors = indicadors;
   }
   public Set getPreguntas() {
       return this.preguntas;
   }
   
   public void setPreguntas(Set preguntas) {
       this.preguntas = preguntas;
   }
}