package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Indicador generated by hbm2java
 */
public class Indicador  implements java.io.Serializable {


	private int idIndicador;
    private Asignatura asignatura;
    private String nomenclaturaIndicador;
    private String descripcionIndicador;
    private Set indicadorIndicadorsForIdIndicadorEntrada = new HashSet(0);
    private Set analisisEstaticos = new HashSet(0);
    private Set indicadorIndicadorsForIdIndicadorSalida = new HashSet(0);

   public Indicador() {
   }

	
   public Indicador(int idIndicador) {
       this.idIndicador = idIndicador;
   }
   public Indicador(int idIndicador, Asignatura asignatura, String nomenclaturaIndicador, String descripcionIndicador, Set indicadorIndicadorsForIdIndicadorEntrada, Set analisisEstaticos, Set indicadorIndicadorsForIdIndicadorSalida) {
      this.idIndicador = idIndicador;
      this.asignatura = asignatura;
      this.nomenclaturaIndicador = nomenclaturaIndicador;
      this.descripcionIndicador = descripcionIndicador;
      this.indicadorIndicadorsForIdIndicadorEntrada = indicadorIndicadorsForIdIndicadorEntrada;
      this.analisisEstaticos = analisisEstaticos;
      this.indicadorIndicadorsForIdIndicadorSalida = indicadorIndicadorsForIdIndicadorSalida;
   }
  
   public int getIdIndicador() {
       return this.idIndicador;
   }
   
   public void setIdIndicador(int idIndicador) {
       this.idIndicador = idIndicador;
   }
   public Asignatura getAsignatura() {
       return this.asignatura;
   }
   
   public void setAsignatura(Asignatura asignatura) {
       this.asignatura = asignatura;
   }
   public String getNomenclaturaIndicador() {
       return this.nomenclaturaIndicador;
   }
   
   public void setNomenclaturaIndicador(String nomenclaturaIndicador) {
       this.nomenclaturaIndicador = nomenclaturaIndicador;
   }
   public String getDescripcionIndicador() {
       return this.descripcionIndicador;
   }
   
   public void setDescripcionIndicador(String descripcionIndicador) {
       this.descripcionIndicador = descripcionIndicador;
   }
   public Set getIndicadorIndicadorsForIdIndicadorEntrada() {
       return this.indicadorIndicadorsForIdIndicadorEntrada;
   }
   
   public void setIndicadorIndicadorsForIdIndicadorEntrada(Set indicadorIndicadorsForIdIndicadorEntrada) {
       this.indicadorIndicadorsForIdIndicadorEntrada = indicadorIndicadorsForIdIndicadorEntrada;
   }
   public Set getAnalisisEstaticos() {
       return this.analisisEstaticos;
   }
   
   public void setAnalisisEstaticos(Set analisisEstaticos) {
       this.analisisEstaticos = analisisEstaticos;
   }
   public Set getIndicadorIndicadorsForIdIndicadorSalida() {
       return this.indicadorIndicadorsForIdIndicadorSalida;
   }
   
   public void setIndicadorIndicadorsForIdIndicadorSalida(Set indicadorIndicadorsForIdIndicadorSalida) {
       this.indicadorIndicadorsForIdIndicadorSalida = indicadorIndicadorsForIdIndicadorSalida;
   }
    
    
}