package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0



/**
 * MatrizAdyacenciaAsociada generated by hbm2java
 */
public class MatrizAdyacenciaAsociada  implements java.io.Serializable {


     private int idMatrizAdyAsoc;
     private IndicadorIndicador indicadorIndicador;
     private VariableLenguistica variableLenguistica;
     private String idUsuario;

    public MatrizAdyacenciaAsociada() {
    }

	
    public MatrizAdyacenciaAsociada(int idMatrizAdyAsoc, IndicadorIndicador indicadorIndicador) {
        this.idMatrizAdyAsoc = idMatrizAdyAsoc;
        this.indicadorIndicador = indicadorIndicador;
    }
    public MatrizAdyacenciaAsociada(int idMatrizAdyAsoc, IndicadorIndicador indicadorIndicador, VariableLenguistica variableLenguistica, String idUsuario) {
       this.idMatrizAdyAsoc = idMatrizAdyAsoc;
       this.indicadorIndicador = indicadorIndicador;
       this.variableLenguistica = variableLenguistica;
       this.idUsuario = idUsuario;
    }
   
    public int getIdMatrizAdyAsoc() {
        return this.idMatrizAdyAsoc;
    }
    
    public void setIdMatrizAdyAsoc(int idMatrizAdyAsoc) {
        this.idMatrizAdyAsoc = idMatrizAdyAsoc;
    }
    public IndicadorIndicador getIndicadorIndicador() {
        return this.indicadorIndicador;
    }
    
    public void setIndicadorIndicador(IndicadorIndicador indicadorIndicador) {
        this.indicadorIndicador = indicadorIndicador;
    }
    public VariableLenguistica getVariableLenguistica() {
        return this.variableLenguistica;
    }
    
    public void setVariableLenguistica(VariableLenguistica variableLenguistica) {
        this.variableLenguistica = variableLenguistica;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }




}