package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0



/**
 * MatrizAdyacencia generated by hbm2java
 */
public class MatrizAdyacencia  implements java.io.Serializable {


     private int idMatriz;
     private IndicadorIndicador indicadorIndicador;
     private Float valorAbsoluto;

    public MatrizAdyacencia() {
    }

	
    public MatrizAdyacencia(int idMatriz, IndicadorIndicador indicadorIndicador) {
        this.idMatriz = idMatriz;
        this.indicadorIndicador = indicadorIndicador;
    }
    public MatrizAdyacencia(int idMatriz, IndicadorIndicador indicadorIndicador, Float valorAbsoluto) {
       this.idMatriz = idMatriz;
       this.indicadorIndicador = indicadorIndicador;
       this.valorAbsoluto = valorAbsoluto;
    }
   
    public int getIdMatriz() {
        return this.idMatriz;
    }
    
    public void setIdMatriz(int idMatriz) {
        this.idMatriz = idMatriz;
    }
    public IndicadorIndicador getIndicadorIndicador() {
        return this.indicadorIndicador;
    }
    
    public void setIndicadorIndicador(IndicadorIndicador indicadorIndicador) {
        this.indicadorIndicador = indicadorIndicador;
    }
    public Float getValorAbsoluto() {
        return this.valorAbsoluto;
    }
    
    public void setValorAbsoluto(Float valorAbsoluto) {
        this.valorAbsoluto = valorAbsoluto;
    }




}