package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {

	private int idPregunta;
    private Asignatura asignatura;
    private String pregunta;
    private String tipoPregunta;
    private String imagenFile;
    private Set respuestas = new HashSet(0);

   public Pregunta() {
   }

	
   public Pregunta(int idPregunta) {
       this.idPregunta = idPregunta;
   }
   public Pregunta(int idPregunta, Asignatura asignatura, String pregunta, String tipoPregunta, String imagenFile, Set respuestas) {
      this.idPregunta = idPregunta;
      this.asignatura = asignatura;
      this.pregunta = pregunta;
      this.tipoPregunta = tipoPregunta;
      this.imagenFile = imagenFile;
      this.respuestas = respuestas;
   }
  
   public int getIdPregunta() {
       return this.idPregunta;
   }
   
   public void setIdPregunta(int idPregunta) {
       this.idPregunta = idPregunta;
   }
   public Asignatura getAsignatura() {
       return this.asignatura;
   }
   
   public void setAsignatura(Asignatura asignatura) {
       this.asignatura = asignatura;
   }
   public String getPregunta() {
       return this.pregunta;
   }
   
   public void setPregunta(String pregunta) {
       this.pregunta = pregunta;
   }
   public String getTipoPregunta() {
       return this.tipoPregunta;
   }
   
   public void setTipoPregunta(String tipoPregunta) {
       this.tipoPregunta = tipoPregunta;
   }
   
   public String getImagenFile() {
		return imagenFile;
	}

	public void setImagenFile(String imagenFile) {
		this.imagenFile = imagenFile;
	}
   
   public Set getRespuestas() {
       return this.respuestas;
   }
   
   public void setRespuestas(Set respuestas) {
       this.respuestas = respuestas;
   }
}