package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {

	private int idRespuesta;
    private Pregunta pregunta;
    private String respuesta;
    private Float peso;
    private Set resultados = new HashSet(0);

   public Respuesta() {
   }

	
   public Respuesta(int idRespuesta, Pregunta pregunta) {
       this.idRespuesta = idRespuesta;
       this.pregunta = pregunta;
   }
   public Respuesta(int idRespuesta, Pregunta pregunta, String respuesta, Float peso, Set resultados) {
      this.idRespuesta = idRespuesta;
      this.pregunta = pregunta;
      this.respuesta = respuesta;
      this.peso = peso;
      this.resultados = resultados;
   }
  
   public int getIdRespuesta() {
       return this.idRespuesta;
   }
   
   public void setIdRespuesta(int idRespuesta) {
       this.idRespuesta = idRespuesta;
   }
   public Pregunta getPregunta() {
       return this.pregunta;
   }
   
   public void setPregunta(Pregunta pregunta) {
       this.pregunta = pregunta;
   }
   public String getRespuesta() {
       return this.respuesta;
   }
   
   public void setRespuesta(String respuesta) {
       this.respuesta = respuesta;
   }
   public Float getPeso() {
       return this.peso;
   }
   
   public void setPeso(Float peso) {
       this.peso = peso;
   }
   public Set getResultados() {
       return this.resultados;
   }
   
   public void setResultados(Set resultados) {
       this.resultados = resultados;
   }
}