package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Resultado generated by hbm2java
 */
public class Resultado  implements java.io.Serializable {


    private int idResultado;
    private Usuario usuario;
    private Respuesta respuesta;

   public Resultado() {
   }

	
   public Resultado(int idResultado, Usuario usuario) {
       this.idResultado = idResultado;
       this.usuario = usuario;
   }
   public Resultado(int idResultado, Usuario usuario, Respuesta respuesta) {
      this.idResultado = idResultado;
      this.usuario = usuario;
      this.respuesta = respuesta;
   }
  
   public int getIdResultado() {
       return this.idResultado;
   }
   
   public void setIdResultado(int idResultado) {
       this.idResultado = idResultado;
   }
   public Usuario getUsuario() {
       return this.usuario;
   }
   
   public void setUsuario(Usuario usuario) {
       this.usuario = usuario;
   }
   public Respuesta getRespuesta() {
       return this.respuesta;
   }
   
   public void setRespuesta(Respuesta respuesta) {
       this.respuesta = respuesta;
   }




}