package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


    private int idUsuario;
    private String usuario;
    private String nombreUsuario;
    private Set resultados = new HashSet(0);
    private Set evaluacions = new HashSet(0);

   public Usuario() {
   }

	
   public Usuario(int idUsuario) {
       this.idUsuario = idUsuario;
   }
   public Usuario(int idUsuario, String usuario, String nombreUsuario, Set resultados, Set evaluacions) {
      this.idUsuario = idUsuario;
      this.usuario = usuario;
      this.nombreUsuario = nombreUsuario;
      this.resultados = resultados;
      this.evaluacions = evaluacions;
   }
  
   public int getIdUsuario() {
       return this.idUsuario;
   }
   
   public void setIdUsuario(int idUsuario) {
       this.idUsuario = idUsuario;
   }
   public String getUsuario() {
       return this.usuario;
   }
   
   public void setUsuario(String usuario) {
       this.usuario = usuario;
   }
   public String getNombreUsuario() {
       return this.nombreUsuario;
   }
   
   public void setNombreUsuario(String nombreUsuario) {
       this.nombreUsuario = nombreUsuario;
   }
   public Set getResultados() {
       return this.resultados;
   }
   
   public void setResultados(Set resultados) {
       this.resultados = resultados;
   }
   public Set getEvaluacions() {
       return this.evaluacions;
   }
   
   public void setEvaluacions(Set evaluacions) {
       this.evaluacions = evaluacions;
   }
}