package slvd.database;
// Generated 28-abr-2015 21:40:29 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * VariableLenguistica generated by hbm2java
 */
public class VariableLenguistica  implements java.io.Serializable {


     private int idVariableLenguistica;
     private Float valorNumerico;
     private String impacto;
     private Set matrizAdyacenciaAsociadas = new HashSet(0);

    public VariableLenguistica() {
    }

	
    public VariableLenguistica(int idVariableLenguistica) {
        this.idVariableLenguistica = idVariableLenguistica;
    }
    public VariableLenguistica(int idVariableLenguistica, Float valorNumerico, String impacto, Set matrizAdyacenciaAsociadas) {
       this.idVariableLenguistica = idVariableLenguistica;
       this.valorNumerico = valorNumerico;
       this.impacto = impacto;
       this.matrizAdyacenciaAsociadas = matrizAdyacenciaAsociadas;
    }
   
    public int getIdVariableLenguistica() {
        return this.idVariableLenguistica;
    }
    
    public void setIdVariableLenguistica(int idVariableLenguistica) {
        this.idVariableLenguistica = idVariableLenguistica;
    }
    public Float getValorNumerico() {
        return this.valorNumerico;
    }
    
    public void setValorNumerico(Float valorNumerico) {
        this.valorNumerico = valorNumerico;
    }
    public String getImpacto() {
        return this.impacto;
    }
    
    public void setImpacto(String impacto) {
        this.impacto = impacto;
    }
    public Set getMatrizAdyacenciaAsociadas() {
        return this.matrizAdyacenciaAsociadas;
    }
    
    public void setMatrizAdyacenciaAsociadas(Set matrizAdyacenciaAsociadas) {
        this.matrizAdyacenciaAsociadas = matrizAdyacenciaAsociadas;
    }




}